name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write


jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --prune --unshallow
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "::set-output name=LATEST_TAG::$LATEST_TAG"

      - name: Calculate next tag
        id: calculate_tag
        run: |
          IFS='.' read -r X Y Z <<< "${{ steps.get_tag.outputs.LATEST_TAG }}"
          Z=$((Z + 1))
          if (( Z > 33 )); then
            Z=0
            Y=$((Y + 1))
          fi
          if (( Y > 33 )); then
            Y=0
            X=$((X + 1))
          fi
          NEW_TAG="${X}.${Y}.${Z}"
          echo "::set-output name=NEW_TAG::$NEW_TAG"

      - name: Create tag
        run: |
          git tag ${{ steps.calculate_tag.outputs.NEW_TAG }}
          git push origin ${{ steps.calculate_tag.outputs.NEW_TAG }}

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.calculate_tag.outputs.NEW_TAG }}
          release_name: Release ${{ steps.calculate_tag.outputs.NEW_TAG }}
          body: |
            **Automatic release created from the main branch.**
            **Full compare**: https://github.com/${{ github.repository }}/compare/${{ steps.get_tag.outputs.LATEST_TAG }}...${{ steps.calculate_tag.outputs.NEW_TAG }}
          draft: false
          prerelease: false
  purge-cdn:
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      - name: purge jsdelivr
        run: |
          sleep 5
          curl https://purge.jsdelivr.net/gh/${{ github.repository }}@latest/
          curl https://purge.jsdelivr.net/gh/${{ github.repository }}/
